# Generated by Django 6.0 on 2025-12-09 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=20)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordenes', to='api.comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr_hash', models.CharField(max_length=255, unique=True)),
                ('asistente_nombre', models.CharField(max_length=100)),
                ('asistente_apellido', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('UTILIZADO', 'Utilizado'), ('ANULADO', 'Anulado')], default='VIGENTE', max_length=20)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.ordencompra')),
            ],
        ),
    ]
